-- lv1 일정 테이블
create table SCHEDULES (
    schedule_id BIGINT AUTO_INCREMENT,
    writer VARCHAR(4) NOT NULL,
    title VARCHAR(10) NOT NULL,
    contents VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(schedule_id),
);

--
-- lv2 유저, 일정 테이블
create table USERS (
    user_id BIGINT AUTO_INCREMENT,
    user_name VARCHAR(4) NOT NULL,
    user_email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(user_id)
);

create table SCHEDULES (
    schedule_id BIGINT AUTO_INCREMENT,
    user_id BIGINT,
    title VARCHAR(10) NOT NULL,
    contents VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(schedule_id),
    FOREIGN KEY(user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);